# Generated by Django 2.1.2 on 2018-11-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('respond_date', models.DateTimeField(auto_now=True, verbose_name='Respond Date')),
                ('description', models.CharField(blank=True, help_text='simple descripton text.', max_length=100, null=True, verbose_name='DESCRIPTION')),
            ],
        ),
        migrations.CreateModel(
            name='InputForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_indi', models.CharField(max_length=50, verbose_name='NAME_INDI')),
                ('social_id', models.CharField(max_length=50, verbose_name='SOCIAL_ID')),
                ('address_indi', models.CharField(max_length=50, verbose_name='ADDRESS_INDI')),
                ('name_enterprise', models.CharField(max_length=50, verbose_name='NAME_ENTERPRISE')),
                ('Business_license_number', models.CharField(max_length=50, verbose_name='BUINESS_LICENSE_NUMBER')),
                ('representative_name', models.CharField(max_length=50, verbose_name='REPRESENTATIVE_NAME')),
                ('industry', models.CharField(max_length=50, verbose_name='INDUSTRY')),
                ('address_ent', models.CharField(max_length=100, verbose_name='ADDRESS_ENT')),
                ('department', models.CharField(max_length=50, verbose_name='DEPARTMENT')),
                ('position', models.CharField(max_length=50, verbose_name='POSITION')),
                ('assigned_task', models.CharField(max_length=50, verbose_name='ASSIGNED_TASK')),
                ('content', models.TextField(verbose_name='CONTENT')),
                ('working_period', models.CharField(max_length=100, verbose_name='WORKING_PERIOD')),
                ('department_a', models.CharField(max_length=50, verbose_name='DEPARTMENT_A')),
                ('name_a', models.CharField(max_length=50, verbose_name='NAME_A')),
                ('position_a', models.CharField(max_length=50, verbose_name='POSITION_A')),
                ('contact_number_a', models.CharField(max_length=50, verbose_name='CONTACT_NUMBER_A')),
                ('purpose', models.CharField(max_length=50, verbose_name='')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
        ),
        migrations.AlterField(
            model_name='applybuffer',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Request Date'),
        ),
    ]
