# Generated by Django 2.1.2 on 2018-11-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_auto_20181105_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputForm',
        ),
    ]
