# Generated by Django 2.1.2 on 2018-10-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181031_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='who',
            field=models.IntegerField(default=0, verbose_name='who'),
        ),
    ]
